### ISSUE TITLE
Android Facebook project: `The type or namespace "FacebookSdk" does not exist in the namespace "Facebook"`

### ISSUE THREAD

**Issue by BioTurboNick** [CommunityToolkit/Maui.NativeLibraryInterop#34]
I set up my environment, I built the Facebook.Android.Binding project in VS successfully, but then trying to build the sample project fails. `The type or namespace "FacebookSdk" does not exist in the namespace "Facebook"`.

VS 17.10.3 on Windows 23H2

Two potentially relevant warnings:
From BINDINGSGENERATOR: BG8601 - `No '<package>' elements found.`
From Metadata.xml: BG8A04 - `Metadata.xml element '<attr path="/api/package[@name='com.microsoft.mauifacebok']" />' matched no nodes.`

**Comment by mikeparker104** [comment]
@BioTurboNick looks like the path in the ```Metadata.xml``` warning (```com.microsoft.mauifacebok```) doesn't match the [value in the sample](https://github.com/CommunityToolkit/Maui.NativeLibraryInterop/blob/c2c6feb25449b90f84eead95de85218f33f9176a/facebook/android/Facebook.Android.Binding/Transforms/Metadata.xml#L9) (```com.microsoft.mauifacebook```). Please can you confirm the path is correct?

**Comment by BioTurboNick** [comment]
...oh lol.

Thank you.
