### ISSUE TITLE
 error NU1101: Unable to find package CommunityToolkit.Maui.NativeLibraryInterop.BuildTasks.

### ISSUE THREAD

**Issue by fourad** [CommunityToolkit/Maui.NativeLibraryInterop#38]
my project used to build nicely and then i started getting this log and i cant build the project  error NU1101: Unable to find package CommunityToolkit.Maui.NativeLibraryInterop.BuildTasks. No packages exist with this id in source(s): /usr/local/share/dotnet/library-packs, nuget.org

**Comment by jeremi-przeorek** [comment]
Hi you need to build your csproj with --configfile flag that will point to this file `template/NuGet.Config`. This NuGet is in separated source.

**Comment by fourad** [comment]
thanks, it works.
