### ISSUE TITLE
Update NativeLibraryInterop.BuildTasks to build bindings for macOS/tvOS 

### ISSUE THREAD

**Issue by drasticactions** [CommunityToolkit/Maui.NativeLibraryInterop#40]
The underlying build tasks used in this repo for maintaining the XCFrameworks using by the bindings supports iOS and Mac Catalyst apps. That supports some app types, but the underlying libraries being bound to may also support additional platforms, like macOS (AppKit) and tvOS. XCFramework itself supports it, as well as the Mac/iOS SDK.

I wanted to add a binding to [SDWebImage](https://github.com/drasticactions/Drastic.SDWebImage/tree/main), so it could be more easily maintained by others, but it supports macOS and tvOS, and I don't want to try and PR support for only half the platforms. If we allow macOS and tvOS, that would open up more opportunities for bindings.

**Comment by kbsanders** [comment]
I am interested in this as well.

I need more AppKit features than a library targeting Mac Catalyst can provide.
Is there any way to work around this limitation until macOS binding support can be added to the repo?

I did stumble across this article, where they use a Bundle/Plugin approach for Mac Catalyst + macOS/AppKit interop.
https://betterprogramming.pub/how-to-access-the-appkit-api-from-mac-catalyst-apps-2184527020b5

Following the instructions in part B, I was able to successfully build their example project in Xcode/Swift, but I don't know enough yet to understand how to get the Bundle/Plugin bindings to work with C# and .NET MAUI.

That's when I discovered the Maui.NativeLibraryInterop repo but ran into trouble as soon as I tried to create bindings for a library targeting macOS.

**Comment by drasticactions** [comment]
So that's different from what I'm suggesting and what I think you want.

You're trying to bring in AppKit APIs into a .NET Mac Catalyst (`net*.0-maccatalyst`) app, for what I assume is a MAUI UI application. I'm requesting to be able to bind macOS Appkit libraries into a .NET macOS (net*.0-macos`) app using these helper functions, so I could add bindings for more supported .NET SDK platforms (`net8.0-tvos`, `net8.0-macos`, etc) that are not used by the MAUI Cross Platform UI Framework.

Apple does not support bringing AppKit APIs into Catalyst except for ones it binds itself, which is why it can best be thought of as using private APIs. You can _technically_ do it using Objective-C selectors and lots of reflection. But this is well beyond the scope of a library like this. This should be officially supported use cases provided by the platform, not hacks.

**Comment by pjcollins** [comment]
Hey @drasticactions we're working to move these build tasks/targets into the .NET mobile workloads, MaciOS work is in progress here https://github.com/xamarin/xamarin-macios/pull/21232. This should bring additional support for projects targeting macOS and tvOS.
