### ISSUE TITLE
AppStore rejects embedded frameworks

### ISSUE THREAD

**Issue by MerlinTHS** [CommunityToolkit/Maui.NativeLibraryInterop#43]
If a MAUI app uses a binding library that embeds (and signs) the framework it binds (like in the GoogleCast example), the app cannot being published to the AppStore.

`[Application Loader Error Output]: Asset validation failed Invalid Bundle. The bundle at '...' contains disallowed nested bundles. (ID: f2e4c051-0fdb-4d8d-9185-adc06bbdf3a8) (90205)
[Application Loader Error Output]: Asset validation failed Invalid Bundle. The bundle at '....' contains disallowed file 'Frameworks'. (ID: dd0764a3-6233-489c-9a28-b97da2236d96) (90206)
[Application Loader Error Output]: The call to the altool completed with a non-zero exit status: 1. This indicates a failure.
`

When the "Embed" setting of the XCode project is set to "Do Not Embed", the app will crash at runtime

`ASI found [dyld] (sensitive) 'Library not loaded: @rpath...`

Is there a way to include iOS frameworks in the csproj file of the app like there is a way for android (`AndroidLibrary`)?

**Comment by raginmari** [comment]
This does not sound like an issue with NLI but rather with the way your bundles are set up. Do you have an example project to reproduce the issue? Which package manager do you use for your native iOS dependencies? I had the best results with Carthage and building the XCFrameworks myself. Have you inspected your frameworks / bundles for invalid entries and searched if other people have similar issues; possibly independently from NLI?

In any case: this is something to keep in mind when using NLI / native bindings: things might break as late as the App Store review stage for the reason you are mentioning as well as code signing issues in your binding library, for example (that is what we are currently dealing with).

**Comment by MerlinTHS** [comment]
I haven't used any package manager. I referenced the downloaded .xcframeworks. The solution was to change embedding to "Do Not Embed" and include the native references in the .csproj file of the binding project via `NativeReference`.
```xml
<NativeReference Include="path/to/your/xcframework">
  <Kind>Framework</Kind>
  <SmartLink>true</SmartLink>
</NativeReference>
```

But you can also use a package manager and embed it that way in the binding project as well.
To sign the native binding wrapper, we used the same iOS Distribution profile as for the app itself.

**Comment by drasticactions** [comment]
You may want to bring this up in [xamarin-macios](https://github.com/xamarin/xamarin-macios) as well to try and get help figuring this out. It could be related to this library helper, but the SDK team would probably know more of how to help you here.

**Comment by dalexsoto** [comment]
Do you have an example on how to repro this? Looks like the xcframework is not in the right place

**Comment by TNT0305** [comment]
I think I am running into the same issues as @MerlinTHS.  It is difficult to make a reproducible example as it all compiles fine, but when you try to publish/archive the .ipa (I'm using transporter), it generates the errors about nested frameworks and/or signing.  As we need to have the app name set up in our app store account, that is not shareable.
In my application, I'm using this more like the intent of the original "SlimBindings" project (using a popular gis mapping framework but simplifying the interface with my own code).  Everything works for me when I debug it on device (hooray!), but when I try to publish, I hit all these issues.
My project layout is:
```
- android
  > ... android native/interop parts, which I have working.  omitted for brevity...
- macios
  - (1) 3rdPartyInterop.Binding.iOS
  - native
    - externals
      > (2) 3rdPartyLib.xcframework (downloaded framework)
    - 3rdPartyInterop
      > ...my code to simplify the interface to 3rdPathLib.xcframework
   > (3) 3rdPartyInterop.xcodeproj
- (4) myProject (the .net 8 maui project that has a ProjectReference to 1)
```

I'm trying to build all this in rider or the dotnet cli.
So, my questions are:
A) how should (2) be referenced in (3)?  ("Do Not Embed", "Embed and Sign", "Do Not Embed")
B) (1) should not even try to be signed, correct?  Should "SmartLink" be true?  Should this binding project include a "NativeReference" to (2)
C) If "Dot not Embed" and no "nativeReference" in 3, should "NativeReference" to (2) be included in (4)?

I have tried various steps with manual codesign at various stages and with the framework included (or not) in various places.  app store verification seems to want the signing of the 3rd party lib to match that of the app (which doesn't make sense to me as I would think the original author signature would be a more useful authenticity audit).

Any guidance would be appreciated.  Thanks!

**Comment by MichaelLHerman** [comment]
I'm having the same issue, but I'm not sure how to get `path/to/your/xcframework`.   My framework is added as an SPM package to my native project.

I tried getting it from the obj folder but then I get signing errors
`<NativeReference Include="$(IntermediateOutputPath)xcode/DerivedData/SourcePackages/checkouts/AmplitudeSessionReplay-iOS/Frameworks/AmplitudeSessionReplay.xcframework">`

```
1>Xamarin.Shared.targets(2442,3): Error : /usr/bin/codesign exited with code 1:
/Users/mikeherman/Repos/Maui.NativeLibraryInterop/template/sample/bin/Debug/net9.0-ios/iossimulator-arm64/MauiSample.app/Frameworks/AmplitudeSessionReplay.framework: replacing existing signature
/Users/mikeherman/Repos/Maui.NativeLibraryInterop/template/sample/bin/Debug/net9.0-ios/iossimulator-arm64/MauiSample.app/Frameworks/AmplitudeSessionReplay.framework: Permission denied
1>Xamarin.Shared.targets(2442,3): Error : Failed to codesign '/Users/mikeherman/Repos/Maui.NativeLibraryInterop/template/sample/bin/Debug/net9.0-ios/iossimulator-arm64/MauiSample.app/Frameworks/AmplitudeSessionReplay.framework': /Users/mikeherman/Repos/Maui.NativeLibraryInterop/template/sample/bin/Debug/net9.0-ios/iossimulator-arm64/MauiSample.app/Frameworks/AmplitudeSessionReplay.framework: replacing existing signature
/Users/mikeherman/Repos/Maui.NativeLibraryInterop/template/sample/bin/Debug/net9.0-ios/iossimulator-arm64/MauiSample.app/Frameworks/AmplitudeSessionReplay.framework: Permission denied
```
