### ISSUE TITLE
Publish NuGet package on nuget.org

### ISSUE THREAD

**Issue by joshardt** [CommunityToolkit/Maui.NativeLibraryInterop#45]
Could you please publish the package `CommunityToolkit.Maui.NativeLibraryInterop.BuildTasks` on nuget.org? It would make things easier for people and me because I have to use build servers for which I don't have the permission to adjust them by my own.

**Comment by pjcollins** [comment]
We are working to move these build tasks/targets into .NET mobile workloads, which will eventually replace the need to use this NuGet package. Once that functionality becomes available we will update this repo and the corresponding documentation. You can track some of the progress of that work in the following PRs:

https://github.com/dotnet/android/pull/9270
https://github.com/xamarin/xamarin-macios/pull/21232
