### ISSUE TITLE
Local aar dependency

### ISSUE THREAD

**Issue by FeschenkoAlex** [CommunityToolkit/Maui.NativeLibraryInterop#48]
Hi. I am trying to utilize Samsung IAP sdk which is distributed as a standalone aar file. The only one way I figured out how to use it inside the native Android project is via this line in build.gradle.kts 

`dependencies {
    compileOnly(files("libs/samsung-iap-6.2.0.aar"))
}`

I was able to use an SDK and sucessfully build project in Android Studio. Binding project was also built  but when I wanted to use the functionality in my app I didnt find built classes. Here is my app's csproj

`<ItemGroup Condition="$(TargetFramework.Contains('android'))">
		<ProjectReference Include="..\android\Billing.Android.Binding\Billing.Android.Binding.csproj" />
	</ItemGroup>

	<ItemGroup Condition="$(TargetFramework.Contains('android'))">
		<AndroidLibrary Include="..\android\native\billing\bin\Release\net8.0-android\outputs\aar\billing-release.aar">
			<Bind>false</Bind>
			<Visible>false</Visible>
		</AndroidLibrary>
	</ItemGroup>`

Is there anything I am doing wrong? Seems there is a problem if native dependency is not distributed via Maven

**Comment by MikhailFrenkel** [comment]
have you tried the following?
`<AndroidLibrary Include="..\android\native\billing\bin\Release\net8.0-android\outputs\deps\samsung-iap-6.2.0.aar">`

**Comment by FeschenkoAlex** [comment]
> have you tried the following? `<AndroidLibrary Include="..\android\native\billing\bin\Release\net8.0-android\outputs\deps\samsung-iap-6.2.0.aar">`

Hi Mikhail. Yes I had this line, nothing really changed :(

**Comment by MichaelFrenkel** [comment]
just to double-check. In your sample code you reference `billing-release.aar` but not `samsung-iap-6.2.0.aar` in `AndroidLibrary`, probably that's why you have runtime exception

**Comment by MikhailFrenkel** [comment]
just to double-check. In your sample code you reference billing-release.aar but not samsung-iap-6.2.0.aar in AndroidLibrary, probably that's why you have runtime exception

**Comment by MikhailFrenkel** [comment]
could you share a solution if possible? it would be easier to understand
have you checked the path `..\android\native\billing\bin\Release\net8.0-android\outputs\aar\samsung-iap-6.2.0.aar`. Is `samsung-iap-6.2.0.aar` for sure located here?

**Comment by FeschenkoAlex** [comment]
Seems I was able to make it work after several retries and VS restarts. @MikhailFrenkel appreciate your help
