### ISSUE TITLE
Unknown type name 'NSUInteger' with Xcode 15.4

### ISSUE THREAD

**Issue by scottkdavis** [CommunityToolkit/Maui.NativeLibraryInterop#51]
### Description

After cloning the repo, open template project in VS Code, set debug target to MacOS, attempt to debug. Receive 9 errors about unknown types for NSUInteger, NSInteger, and NSIntegerMax in NSObjCRuntime.h file buried deep in Xcode.app under the iPhoneOS17.5 folder. 

If I removed iOS in the project file so only net8.0-maccatalyst is listed as a target framework. I also receive NS_FORMAT_ARGUMENT error in the NSString.h file inside Xcode.app. 

Searching the internet, this seems to be an issue with Xcode 15.4 that doesn't exist in 15.2. Maui 8 is supposed to support 15.4

Like most people who are probably looking at the Maui.NativeLibraryInterop, I'm an Xcode noob and have no idea how to troubleshoot this issue. I assume I cannot roll Xcode back to 15.2 because experience shows me that Maui needs a very specific version to work.

### Steps to Reproduce

Close repo, attempt to run debug "template" project without modification.

### Environment

- OS: MacOS Sonoma 14.5 (M1 chip)
- .NET MAUI: 8
- Target platforms: MacOS, iOS

**Comment by rachelkang** [comment]
Hi, @scottkdavis - thanks for checking out the template! If you are still experiencing issues, please attach a binlog so that the team can take a closer look at your scenario.

**Comment by scottkdavis** [comment]
I am unsure what you are looking for. A binlog for compile errors? Is that even a thing?

I cannot give you a reproduction repo because I am using your unmodified repo. I have cloned the repo, VS Code for Mac, "Open Folder" select the "template" folder that includes the "newBinding.sln" file. Click run and debug, select C# debugger. Project fails to compile.   (BTW, I get 121 errors if I try to compile the Facebook sample project, so this is not limited to the template project)

Here are the errors. 
[{
	"resource": "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h",
	"owner": "msCompile",
	"code": "G1B97B5E7",
	"severity": 8,
	"message": "unknown type name 'NSUInteger' [/Users/scottkdavis/Documents/Maui.NativeLibraryInterop/template/macios/NewBinding.MaciOS.Binding/NewBinding.MaciOS.Binding.csproj::TargetFramework=net8.0-maccatalyst]",
	"source": "cpp",
	"startLineNumber": 615,
	"startColumn": 74,
	"endLineNumber": 615,
	"endColumn": 74
},{
	"resource": "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h",
	"owner": "msCompile",
	"code": "G1B97B5E7",
	"severity": 8,
	"message": "unknown type name 'NSUInteger' [/Users/scottkdavis/Documents/Maui.NativeLibraryInterop/template/macios/NewBinding.MaciOS.Binding/NewBinding.MaciOS.Binding.csproj::TargetFramework=net8.0-maccatalyst]",
	"source": "cpp",
	"startLineNumber": 615,
	"startColumn": 104,
	"endLineNumber": 615,
	"endColumn": 104
},{
	"resource": "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h",
	"owner": "msCompile",
	"code": "G1B97B5E7",
	"severity": 8,
	"message": "unknown type name 'NSInteger' [/Users/scottkdavis/Documents/Maui.NativeLibraryInterop/template/macios/NewBinding.MaciOS.Binding/NewBinding.MaciOS.Binding.csproj::TargetFramework=net8.0-maccatalyst]",
	"source": "cpp",
	"startLineNumber": 631,
	"startColumn": 24,
	"endLineNumber": 631,
	"endColumn": 24
},{
	"resource": "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h",
	"owner": "msCompile",
	"code": "G1B97B5E7",
	"severity": 8,
	"message": "unknown type name 'NSUInteger' [/Users/scottkdavis/Documents/Maui.NativeLibraryInterop/template/macios/NewBinding.MaciOS.Binding/NewBinding.MaciOS.Binding.csproj::TargetFramework=net8.0-maccatalyst]",
	"source": "cpp",
	"startLineNumber": 639,
	"startColumn": 20,
	"endLineNumber": 639,
	"endColumn": 20
},{
	"resource": "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h",
	"owner": "msCompile",
	"code": "G1B97B5E7",
	"severity": 8,
	"message": "unknown type name 'NSUInteger' [/Users/scottkdavis/Documents/Maui.NativeLibraryInterop/template/macios/NewBinding.MaciOS.Binding/NewBinding.MaciOS.Binding.csproj::TargetFramework=net8.0-maccatalyst]",
	"source": "cpp",
	"startLineNumber": 644,
	"startColumn": 20,
	"endLineNumber": 644,
	"endColumn": 20
},{
	"resource": "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h",
	"owner": "msCompile",
	"code": "G1B97B5E7",
	"severity": 8,
	"message": "unknown type name 'NSInteger' [/Users/scottkdavis/Documents/Maui.NativeLibraryInterop/template/macios/NewBinding.MaciOS.Binding/NewBinding.MaciOS.Binding.csproj::TargetFramework=net8.0-maccatalyst]",
	"source": "cpp",
	"startLineNumber": 649,
	"startColumn": 17,
	"endLineNumber": 649,
	"endColumn": 17
},{
	"resource": "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h",
	"owner": "msCompile",
	"code": "G1B97B5E7",
	"severity": 8,
	"message": "unknown type name 'NSInteger' [/Users/scottkdavis/Documents/Maui.NativeLibraryInterop/template/macios/NewBinding.MaciOS.Binding/NewBinding.MaciOS.Binding.csproj::TargetFramework=net8.0-maccatalyst]",
	"source": "cpp",
	"startLineNumber": 657,
	"startColumn": 14,
	"endLineNumber": 657,
	"endColumn": 14
},{
	"resource": "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h",
	"owner": "msCompile",
	"code": "GA50814E8",
	"severity": 8,
	"message": "use of undeclared identifier 'NSIntegerMax' [/Users/scottkdavis/Documents/Maui.NativeLibraryInterop/template/macios/NewBinding.MaciOS.Binding/NewBinding.MaciOS.Binding.csproj::TargetFramework=net8.0-maccatalyst]",
	"source": "cpp",
	"startLineNumber": 657,
	"startColumn": 37,
	"endLineNumber": 657,
	"endColumn": 37
},{
	"resource": "/Users/scottkdavis/.nuget/packages/communitytoolkit.maui.nativelibraryinterop.buildtasks/0.0.1-pre1/tools/Common.macios.targets",
	"owner": "msCompile",
	"code": "SHRP0000",
	"severity": 8,
	"message": "Parsing 1 header files... [/Users/scottkdavis/Documents/Maui.NativeLibraryInterop/template/macios/NewBinding.MaciOS.Binding/NewBinding.MaciOS.Binding.csproj::TargetFramework=net8.0-maccatalyst]",
	"source": "cpp",
	"startLineNumber": 168,
	"startColumn": 5,
	"endLineNumber": 168,
	"endColumn": 5
}]
