### ISSUE TITLE
NativeLibraryInterop Package Missing from Nuget

### ISSUE THREAD

**Issue by HomeroLara** [CommunityToolkit/Maui.NativeLibraryInterop#56]
### Description

I cannot find the 'CommunityToolkit.Maui.NativeLibraryInterop.BuildTasks' nuget package. I've tried using VS For Mac, VS on Windows, Rider and also on Nuget.org.

My development environment:
- Net 8.0.403
- Maui Workload 8.0.82/8.0.100        SDK 8.0.400

Has this package been removed or renamed? 

Thanks!

### Steps to Reproduce

1. From Visual Studio or Rider, create a .Net MAUI project.
2. Right click the solution and select Manage Nuget Packages ( be sure to enable prereleases by checking the 'Include Prereleases' box.
3. Searching for 'CommunityToolkit.Maui.NativeLibraryInterop.BuildTasks' or 'CommunityToolkit.Maui.NativeLibraryInterop' returns zero results. 
4. Nuget.org and command line also fail to find this package.

### Link to public reproduction project repository

https://github.com/CommunityToolkit/Maui.NativeLibraryInterop

### Environment

- OS: Mac ( Apple M2 Max ), Sonoma 14.6.1
- .NET MAUI: Net 8.0.403 / Maui Workload 8.0.82/8.0.100        SDK 8.0.400
- Target platforms: Android and iOS

**Comment by rachelkang** [comment]
Hi @HomeroLara - the BuildTasks package are not available on NuGet. Please add the following package reference to your NuGet.config in order to use it successfully: https://github.com/CommunityToolkit/Maui.NativeLibraryInterop/blob/ab58d1dd6de3332a1d0ef80a11ea69f0f08f9f0a/nuget.config#L4

Eventually, we hope to better consolidate this dependency as well!

**Comment by HomeroLara** [comment]
> Hi [@HomeroLara](https://github.com/HomeroLara) - the BuildTasks package are not available on NuGet. Please add the following package reference to your NuGet.config in order to use it successfully:
> 
> [Maui.NativeLibraryInterop/nuget.config](https://github.com/CommunityToolkit/Maui.NativeLibraryInterop/blob/ab58d1dd6de3332a1d0ef80a11ea69f0f08f9f0a/nuget.config#L4)
> 
> Line 4 in [ab58d1d](/CommunityToolkit/Maui.NativeLibraryInterop/commit/ab58d1dd6de3332a1d0ef80a11ea69f0f08f9f0a)
> 
>  <add key="maui-nativelibraryinterop" value="https://pkgs.dev.azure.com/xamarin/public/_packaging/maui-nativelibraryinterop/nuget/v3/index.json" /> 
> Eventually, we hope to better consolidate this dependency as well!

Thanks @rachelkang !
