### ISSUE TITLE
Objective Sharpie `error: invalid SDK 'iphoneos-18.0'

### ISSUE THREAD

**Issue by Peru-S** [CommunityToolkit/Maui.NativeLibraryInterop#62]
Hi, 
I cloned this repo and ran `dotnet build` in `maui.nativelibraryinterop/template/macios/NewBinding.MaciOS.Binding` to generate the API defs (as described in Rachel Kang's excellent tutorial here: https://devblogs.microsoft.com/dotnet/native-library-interop-dotnet-maui/)

I see the following error:

```
.nuget/packages/communitytoolkit.maui.nativelibraryinterop.buildtasks/0.0.1-pre1/tools/Common.macios.targets(168,5): error SHRP0000: error: invalid SDK 'iphoneos18.0'
```

Also `sharpie xcode -sdks` returns nothing. [My xcode is in an external HDD, and `xcode-select -p` returns the correct location]

Not sure what the problem is. Is iOS18.0 too new?

[`sharpie update` throws an error too.]

**Comment by Peru-S** [comment]
I symlinked `ln -s` /Applications/Xcode.app/ and still it doesn't work.
On a different machine with Xcode with SDK ios17.5 `sharpie xcode -sdks` works / builds the API defs.

Will there be a newer Objective Sharpie released? (Guessing it's not working with 18.0?)

**Comment by Peru-S** [comment]
Thank you. `sharpie xcode -x` works :)
However, I tried it with the net8.0 (Which doesn't work with XCode 16) and net9.0 (your latest in-progress PR).
Your PR net9.0 requires manual `sharpie bind` for which I couldn't find the right command line parameters to work with the template.

**Do you have a full example for invoking `sharpie bind`?**

I tried the following:

```sh
native/NewBinding > sharpie bind -x /blah/ -sdk iphoneos18.0 -o ../../NewBinding.MaciOS.Binding -scope ./NewBinding/ ./NewBinding/NewBinding.h   -c -Ibuild/Release-iphoneos/NewBinding.framework/Headers/
``` 

and the result is this:

```

Binding...
  [write] ApiDefinitions.cs

Binding Analysis:
  Automated binding is complete, but there are a few APIs which have been flagged with [Verify] attributes. While the entire binding should be audited for best API design practices, look more closely at APIs with the following Verify attribute hints:
... (lots of boiler plate text)


Done.
```

The final `ApiDefinitions.cs` has 

```
using Foundation;

[Static]
[Verify (ConstantsInterfaceAssociation)]
partial interface Constants
{
	// extern double NewBindingVersionNumber;
	[Field ("NewBindingVersionNumber", "__Internal")]
	double NewBindingVersionNumber { get; }

	// extern const unsigned char[] NewBindingVersionString;
	[Field ("NewBindingVersionString", "__Internal")]
	byte[] NewBindingVersionString { get; }
}

``` 

which is not the API but ... <i> something </i> else?

I wonder if the net9.0 version can be made to use sharpie automatically just like the net8.0 (with maybe the `-x` option in the csproj perhaps?). If not, docs for the manual step will be super helpful. (the sharpie docs/interop docs are barely sufficient/usable).

**Comment by Peru-S** [comment]
Let me summarize the question:

**For the [dotnet9 PR](https://github.com/CommunityToolkit/Maui.NativeLibraryInterop/pull/55#issuecomment-2489827073), what's the `sharpie` command to regenerate the `template` API cs file from swift/objc?**

@pjcollins  / @rachelkang FYI

Thank you!

**Comment by pjcollins** [comment]
> **For the [dotnet9 PR](https://github.com/CommunityToolkit/Maui.NativeLibraryInterop/pull/55#issuecomment-2489827073), what's the `sharpie` command to regenerate the `template` API cs file from swift/objc?**

For .NET 9 and Xcode 16.0, the sharpie command you'd run against the template should look something like this (from the `template` folder);

```
template % sharpie bind --output=sharpie-out --namespace=NewBindingMaciOS --sdk=iphoneos18.0 --scope=macios/NewBinding.MaciOS.Binding/bin/Debug/net9.0-ios/NewBinding.MaciOS.Binding.resources/NewBindingiOS.xcframework/ios-arm64/NewBinding.framework/Headers macios/NewBinding.MaciOS.Binding/bin/Debug/net9.0-ios/NewBinding.MaciOS.Binding.resources/NewBindingiOS.xcframework/ios-arm64/NewBinding.framework/Headers/NewBinding-Swift.h
```
Which should produce an updated `sharpie-out/ApiDefinitions.cs` file.

**Comment by Peru-S** [comment]
Thank you @pjcollins ! Your command *seems* to work (I will spend a bit more time as the headers are out of date from a stale Debug build - I will report back soon).

Your doc update looks good (I checked/verified iOS only, not Android). Not sure if anyone uses Xcode from an external HDD - if so your pro tip of `sharipe bind -x /path/to/Xcode.app` might be relevant to add in your `.md` update.

**Comment by pjcollins** [comment]
Thanks! I'll mark this as resolved, let us know if you run into any other issues here.
