### ISSUE TITLE
Clarification Needed on Method Name Transformation for Android Binding in Sample Project

### ISSUE THREAD

**Issue by MatanYamin** [CommunityToolkit/Maui.NativeLibraryInterop#63]
Hello, and thank you for this amazing project!

I’ve been working with the sample project included in the Native Library Interop repository and noticed something curious about how method names are transformed in the Android and iOS bindings.

**Observation**
In the Android and iOS sample projects, there is a method called getString. In the MainPage, we invoke this method as GetString (with a capital G). Here’s what I observed:

**1. iOS:**

The transformation is explicitly defined in ApiDefinition.cs:

```
[Static]
[Export ("getStringWithMyString:")]
string GetString(string myString);
```

This is straightforward and clear. We explicitly specify the PascalCase version GetString, which works as expected.

**2. Android:**

- I couldn’t find any explicit place where getString is transformed into GetString.
- Yet, it works! When I invoke GetString, the call works perfectly.
- However, when I attempt to call getString (lowercase g), it does not work.

**Experiment**
To better understand the behavior, I added a second method getString2 in the Android native library.

1. When I called GetString2 (with a capital G), it worked fine.
2. When I called getString2 (lowercase g), it did not work.

Question

1. Is the transformation to PascalCase (getString → GetString) required for Android? If so, where is this behavior defined?
2. Does this mean that for Android, all method names must follow this PascalCase convention when invoked from .NET (e.g., GetString, GetString2, etc.)?
3. For iOS, it seems the ApiDefinition.cs provides flexibility, allowing us to explicitly name the methods. Is this behavior consistent across both platforms?

Any clarification on where and how this transformation happens for Android would be greatly appreciated. It’s a bit confusing as it’s not as explicitly defined as it is for iOS.

**Thank you for your help and for maintaining this great project!**

**Comment by pjcollins** [comment]
Hi @MatanYamin, thanks for trying this out and for the question! I can link to a few resources related to the .NET for Android Java binding process which will hopefully be helpful.

You've correctly noticed that .NET for Android automatically performs a pascal case transformation when binding Java. We do this in an attempt to better align with .NET naming conventions. We have a couple of mentions of this behavior in the [Customizing namespaces](https://learn.microsoft.com/dotnet/android/binding-libs/customizing-bindings/namespace-customization) section of our [Bind java libraries docs](https://learn.microsoft.com/dotnet/android/binding-libs/binding-java-libs).

There are a couple of options for customizing this behavior similar to the ApiDefinition.cs file used for iOS that you've mentioned. The most relevant equivalent is going to be the [`Metadata.xml` file](https://learn.microsoft.com/dotnet/android/binding-libs/customizing-bindings/java-bindings-metadata#metadataxml-transform-file). For namespaces, there is also an `@(AndroidNamespaceReplacement)` item mentioned in the namespaces doc above that can be added to your .csproj file.

To change the name of the method, you _should_ be able to add something like this to your `Metadata.xml` file:

```xml
<attr path="/api/package[@name='com.example.newbinding']/class[@name='DotnetNewBinding']/method[@name='getString']"
    name="managedName">newGetStringName</attr>
```

The .NET for Android generator source code can be found at https://github.com/dotnet/java-interop -- feel free to browse that repo for any other related comments/issues that may be useful.
